---

- name: provision myec2 instance
  hosts: local
  connection: local
  gather_facts: False
  tags: redhatec2
  vars:
    instance_type: t2.micro
    security_group: DefaultServerGroup1
    image: ami-67589505
    keypair: gwkeys
    region: ap-southeast-2
    count: 1

# Task that will be used to Launch/Create an EC2 Instance
  tasks:
    - name: Create security group
      local_action:
        module: ec2_group
        name: "{{ security_group }}"
        description: Security Group for MyServer
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
        register: basic_firewall
    - name: Launch MyEC2 Instance
      local_action: ec2
        group={{ security_group }}
        instance_type={{ instance_type}}
        image={{ image }}
        wait=true
        region={{ region }}
        keypair={{ keypair }}
        count={{count}}
      register: ec2

    - name: Add the MyEC2 instance to the local host group
      local_action: lineinfile
        dest="./hosts"
        regexp={{ item.public_ip }}
        insertafter="[webserver]" line={{ item.public_ip }}
      with_items: "{{ ec2.instances }}"


    - name: Wait for SSH to come up
      local_action: wait_for
        host={{ item.public_ip }}
        port=22
        state=started
      with_items: "{{ ec2.instances }}"
    - name: Add tag to Instance(s)
      local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
      with_items: "{{ ec2.instances }}"
      args:
        tags:
          Name: MyTestWebserver
