---

- ec2:
    key_name: gwkeys
    instance_type: t2.micro
    image: ami-67589505
    wait: yes
    group: DefaultServerGroup
    count: 1
    region: ap-southeast-2
    vpc_subnet_id: subnet-ea500f8d
    assign_public_ip: yes


#- name: Create a Ec2 instance
#  hosts: localhost
#  gather_facts: False
#  vars:
#    key_name: gwkeys
#    instance_type: t2.micro
#    security_group: DefaultServerGroup1
#    image: ami-67589505
#    region: ap-southeast-2
#  tasks:
#      ec2:
#        key_name: "{{ key_name }}"
#        group: "{{ security_group }}"
#        instance_type: "{{ instance_type }}"
#        image: "{{ image }}"
#        wait: True
#        region: "{{ region }}"
#        count: 1
#      register: ec2

#    - name: Add the new instances to host group
#      add_host: hostname={{item.public_ip}} groupname=deploy
#      with_items: "{{ ec2.instances }}"

#    - name: Wait for the instances to boot
#      wait_for: host={{item.public_dns_name}} port=22 delay=60 timeout=320 state=started
#      with_items: "{{ ec2.instances }}"

#    - name: Create a volume and attach it
#      ec2_vol: volume_size=10 instance={{item.id}}
#      with_items: "{{ ec2.instances }}"

# deploy
#- name: Configure instance
#  hosts: deploy
#  remote_user: root

# start the firewalld

#  tasks:
#    - name: Ensure firewall service is up and running
#      service: name=httpd state=started
