---
# Create ec2 instance
- name: Ec2 instances
  hosts: local
  connection: local
  remote_user: root
  gather_facts: false

  vars:
      keypair: gwkeys
      instance_type: t2.micro
      security_group: DefaultServerGroup1
      image: ami-67589505

  tasks:
    - name: Launch instance
      ec2: keypair={{keypair}} group={{security_group}}
           instance_type={{instance_type}} image={{image}}
           wait=true count=1
      register: ec2

    - name: Add the new instances to host group
      add_host: hostname={{item.public_ip}} groupname=deploy
      with_items: ec2.instances

    - name: Wait for the instances to boot
      wait_for: host={{item.public_dns_name}} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

    - name: Create a volume and attach it
      ec2_vol: volume_size=10 instance={{item.id}}
      with_items: ec2.instances


# deploy
- name: Configure instance
  hosts: deploy
  remote_user: root

# start the firewalld

  tasks:
    - name: Ensure firewall service is up and running
      service: name=httpd state=started
