---

- name: Create Docker Container
  hosts: localhost
  connection: local  
  remote_user: root
  tasks:
    - name: include variables
      vars_files: vars.yml
    - name: Create Container
      docker_container:
        name: "{{ name }}"
        image: "{{ image }}"
        ports:
          - "{{ src_port }}:{{ dest_port }}"
        volumes:
          - "{{ src_vol }}:{{ dest_vol }}"
        privileged: "{{ privileged }}"
    - name: Create Systemd Unit File as docker-{{ name }}.service
      template: src=systemd.j2 dest=/etc/systemd/system/docker-{{ name }}.service
    - name: reload systemd daemon
      command: systemctl daemon-reload 
    - name: Start & Enable docker-{{ name }} service
      service:
        name: docker-{{ name }}
        state: started
        enabled: yes
    - name: check container status
      command: docker ps
      register: result
    - debug: var=result.stdout
