---

# Provision and Configure EC2 Instance
- include: configEc2.yml

# Congigure Docker Container
- include: configDocker.yml

# Deploy Nginx and check nginx
- include: confNgnx.yml

# Monitor Continer
#- include: monitorContainer.yml


