---

- hosts: all
  remote_user: root
  vars_files:
    - all.yml

- tasks:
   - file:
       path: /tmp/nginx
       state: directory
       mode: 0755
     become: yes
     become_user: root

- name: Put the nginx.conf file in place
  copy:
    content: "{{ nginx_conf }}"
    dest: "{{ nginx_base_directory }}/nginx.conf"
    mode: '0644'
  notify: 'restart-docker-nginx'

- name: Copy the default html
  copy:
    src: "{{ nginx_static_html_directory }}/"
    dest: "{{ nginx_base_directory }}/defaults"
    mode: '0644'
  notify: 'restart-docker-nginx'

- name: create directory for conf.d nginx
  file:
    path: "{{ nginx_reverse_proxy_config_directory }}"
    state: directory

- name: deploy reverse proxy configurations
  template:
    src: reverse-proxy.conf.j2
    dest: "{{ nginx_reverse_proxy_config_directory }}/{{ item.config_name }}.conf"
  with_items: "{{ nginx_reverse_proxy_proxies }}"
  notify: 'restart-docker-nginx'

- name: Start the nginx docker container
  docker_container:
    image: "nginx:{{ nginx_docker_tag }}"
    name: "{{ nginx_container_name }}"
    volumes: '{{ nginx_exposed_volumes }}'
    ports: '{{ nginx_published_ports }}'
    exposed_ports: '{{ nginx_exposed_ports }}'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_options:
      tag: "{{ nginx_container_name }}"

- meta: flush_handlers

- include_tasks: test.yml
